### ISSUE TITLE
Updating to v7 causes C# language mismatch

### ISSUE THREAD

**Issue by Piedone** [khellang/Scrutor#268]
This is very strange, but this is what happens:

With Scrutor v6.1.0 everything is fine. After updating to v7.0.0 we get a build error from [this line](https://github.com/Lombiq/Helpful-Extensions/blob/5d71c9ab4cc9307727ccc7f8f5d3cf77eac44828/Lombiq.HelpfulExtensions/Controllers/OrchardRecipeMigrationAdminController.cs#L98) from a project using it:

> error CS8652: The feature 'params collections' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.

See the build [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/20132762229/job/57778120190).

Note the following:

- The `JObject.FromObject()` call is just using `System.Text.Json.Nodes.JObject`. That method doesn't use `params` and I don't understand how the error is related to its signature:
```c#
public static JsonObject? FromObject(object? obj, JsonSerializerOptions? options = null)
```
- This is part of a larger solution, [this one](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions) (other projects in it use Scrutor too).
- All projects in the solution target .NET 8 and use C# 12.

I suspect this related to https://github.com/khellang/Scrutor/pull/265 and .NET 10 and doesn't happen if the project targets .NET 10 (what it soon will have).

**Comment by khellang** [comment]
Hi @Piedone! I'm not sure I follow. How does the version of Scrutor affect the language features used in your source code? And what do you think I can/should do about it? 😅  The .NET 10 bump was a simple additional target framework. If you don't target .NET 10, you'd probably end up with the old .NET 8 target.

**Comment by Piedone** [comment]
I'm not sure :). But with Scrutor v6.1.0, everything is fine, with v7.0.0 I get the above error, with nothing else changing.

Maybe the issue is that package references leak through, and .NET 8 projects shouldn't use e.g. v10 of `Microsoft.Extensions.DependencyInjection.Abstractions`. In Orchard Core, we've overcome this with conditional package references like the ones here: https://github.com/OrchardCMS/OrchardCore/blob/0b7b4a335e861d50a80f1280fab81f26b0d9d9fb/Directory.Packages.props#L88

**Comment by Piedone** [comment]
As expected, this doesn't happen with .NET 10.

**Comment by khellang** [comment]
I think what has happened is that the `LangVersion` is set to `latest`. I think that means latest that the SDK supports - irrespective of the target framework, which means that when the SDK was updated to .NET 10, even the .NET 8 target was built using C# 14. I can try to remove the explicit `LangVersion` and publish a new version to see if tageting .NET 8 will work.

**Comment by Piedone** [comment]
That sounds like it, yeah.
